version: '3.1'

services:
  db:
    container_name: db
    image: sameersbn/postgresql:10-2
    env_file:
       - ".env"
    environment:
      DB_USER: $BD_USER
      DB_PASS: $DB_PASS
      DB_NAME: $DB_NAME
    restart: always
    ports:
      - 5432:5432
    networks:
      - botnet
    volumes:
      - ./postgres:/var/lib/postgresql

  tgbot:
    container_name: bot
    build:
      context: .
    command: python app.py
    networks:
      - botnet
    restart: always
    env_file:
      - ".env"
    volumes:
      - .:/src
    # Бот стартует после запуска базы
#    depends_on:
#      - db

# указываются используемые сети
networks:
  botnet:
    # указывается драйвер сети
    driver: bridge