from . import help
from . import start
from . import SU
from . import horoshope
from . import Prediction
from . import profile
from . import compatibility
from . import compability_name
from . import test_wordk_with_table
from . import sheduler
from . import test_pdf
from . import echo
